swagger: '2.0'
info:
  version: "3.0.0"
  title: AutoCAD.io
schemes: ['https']
host: api.autocad.io
consumes:
  - application/json
produces:
  - application/json
parameters:
  call-id:
    name: call-id
    in: path
    type: string
    required: true
  function-id:
    name: function-id
    in: path
    type: string
    required: true
paths:
  /calls:
    get:
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/FunctionCall'
    post:
      parameters:
        - name: call
          in: body
          schema:
            $ref: '#/definitions/FunctionCall'
          required: true
      responses:
        200:
          description: OK
  /calls/{call-id}:
    parameters:
        - $ref: '#/parameters/call-id'
    get:
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/FunctionCall'
  /functions:
    get:
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/FunctionDefinition'
    post:
      parameters:
        - name: function
          in: body
          schema:
            $ref: '#/definitions/FunctionDefinition'
          required: true
      responses:
        200:
          description: OK
    patch:
      parameters:
        - name: function
          in: body
          schema:
            $ref: '#/definitions/FunctionDefinition'
          required: true
      responses:
        200:
          description: OK
  /functions/{function-id}:
    parameters:
        - $ref: '#/parameters/function-id'
    get:
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/FunctionDefinition'
  /functions/{function-id}/Versions:
    parameters:
        - $ref: '#/parameters/function-id'
    get:
      responses:
        200:
          description: Success
          schema:
            type: array
            items: 
              type: integer
  /functions/{function-id}/CurrentVersion:
    parameters:
        - $ref: '#/parameters/function-id'
    get:
      responses:
        200:
          description: Success
          schema:
            type: integer
    put:
      parameters:
        - name: version
          in: body
          schema:
            type: integer
      responses:
        200:
          description: Success
definitions:
  FunctionCall:
    type: object
    properties:
      Id:
        type: string
      FunctionName:
        type: string
  FunctionDefinition:
    type: object
    properties:
      Name:
        type: string
      RequiredEngineVersion:
        type: string
      Version:
        type: integer
